<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit46bb1cc640fc07a3810c485c1eb3489a
{
    public static $files = array (
        'ab8202fdaa7689cd9dcdacf8c6fba20d' => __DIR__ . '/..' . '/planetteamspeak/ts3-php-framework/libraries/TeamSpeak3/TeamSpeak3.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {

        }, null, ClassLoader::class);
    }
}
